export const productData = [
  {
    name: "아이폰 15 Pro",
    slug: "iphone-15-pro",
    description: "티타늄 디자인과 A17 Pro 칩이 탑재된 최신 아이폰",
    price: 1550000,
    stock: 50,
    categorySlug: "smartphones",
  },
  {
    name: "갤럭시 S24 Ultra",
    slug: "galaxy-s24-ultra",
    description: "S Pen 지원과 AI 기능이 강화된 삼성 플래그십 스마트폰",
    price: 1599000,
    stock: 30,
    categorySlug: "smartphones",
  },
  {
    name: "맥북 프로 16인치",
    slug: "macbook-pro-16",
    description: "M3 Max 칩을 탑재한 고성능 노트북",
    price: 4290000,
    stock: 20,
    categorySlug: "laptops",
  },
  {
    name: "LG 그램 17",
    slug: "lg-gram-17",
    description: "초경량 17인치 노트북, 장시간 배터리 지속",
    price: 1990000,
    stock: 40,
    categorySlug: "laptops",
  },
  {
    name: "LG 디오스 냉장고",
    slug: "lg-dios-refrigerator",
    description: "인스타우브 냉장고, 4도어 타입",
    price: 3500000,
    stock: 15,
    categorySlug: "refrigerators",
  },
  {
    name: "삼성 비스포크 냉장고",
    slug: "samsung-bespoke-refrigerator",
    description: "커스터마이징 가능한 스마트 냉장고",
    price: 3200000,
    stock: 12,
    categorySlug: "refrigerators",
  },
  {
    name: "LG 트롬 세탁기",
    slug: "lg-trom-washing-machine",
    description: "AI 직세탁 기능이 있는 세탁기",
    price: 1890000,
    stock: 25,
    categorySlug: "washing-machines",
  },
  {
    name: "삼성 베스킷 세탁기",
    slug: "samsung-bespan-washing-machine",
    description: "빨래바구니가 내장된 올인원 세탁기",
    price: 2100000,
    stock: 18,
    categorySlug: "washing-machines",
  },
  {
    name: "아이패드 프로 12.9",
    slug: "ipad-pro-12-9",
    description: "M2 칩을 탑재한 프리미엄 태블릿",
    price: 1490000,
    stock: 35,
    categorySlug: "electronics",
  },
  {
    name: "갤럭시 탭 S9 Ultra",
    slug: "galaxy-tab-s9-ultra",
    description: "대형 화면의 안드로이드 태블릿",
    price: 1390000,
    stock: 28,
    categorySlug: "electronics",
  },
];

